name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}        
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}        
      - name: install modules
        working-directory: ./client
        run: npm install
      - name: build production project
        working-directory: ./client
        run: npm run build:prod
      - name: linting typescript
        working-directory: ./client
        run: npm run lint:ts
      - name: linting css
        working-directory: ./client
        run: npm run lint:scss
      - name: unit testing
        working-directory: ./client
        run: npm run test:unit
      - name: build storybook
        working-directory: ./client
        run: npm run storybook:build
      - name: screenshot testing
        working-directory: ./client
        run: npm run test:ui:ci
